RushHour.Web/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using RushHour.Web.Areas.HelpPage.ModelDescriptions;
using RushHour.Web.Areas.HelpPage.Models;

namespace RushHour.Web.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

RushHour.Web/Controllers/AuthenticationController.cs
namespace RushHour.Web.Controllers
{
    using System.Web.Mvc;
    using Generic;
    using Models.Binding.User;
    using Services.Tools.Messages;

    public class AuthenticationController : BaseController
    {
        [HttpGet]
        public ActionResult Login()
        {
            if (AuthenticationManager.LoggedUser == null)
                return View();


            AddError(GlobalMessages.AlreadyLoggedIn());
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult Login(LoginBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (AuthenticationManager.LoggedUser != null)
            {
                AddError(GlobalMessages.AlreadyLoggedIn());
                return RedirectToAction("Index", "Home");
            }

            AuthenticationManager.Authenticate(model);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Register()
        {

            if (AuthenticationManager.LoggedUser == null)
                return View();


            AddError(GlobalMessages.AlreadyLoggedIn());
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult Register(RegisterBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (AuthenticationManager.LoggedUser != null)
            {
                AddError(GlobalMessages.ShouldLogoutBeforeRegister());
                return RedirectToAction("Index", "Home");
            }

            AuthenticationManager.Register(model);
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Logout()
        {
            if (AuthenticationManager.LoggedUser == null)
            {
                AddError(GlobalMessages.NotLoggedIn());
                return RedirectToAction("Index", "Home");
            }
            AuthenticationManager.Logout();
            return RedirectToAction("Index", "Home");
        }
    }
}

RushHour.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    @if (RushHour.Web.AuthenticationManager.LoggedUser != null)
                    {
                        <li>@Html.ActionLink("Users", "Index", "Users", new {area = ""}, null)</li>
                        <li>@Html.ActionLink("Appointments", "Index", "Appointments", new {area = ""}, null)</li>
                        <li>@Html.ActionLink("Activities", "Index", "Activities", new {area = ""}, null)</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Authentication", new {area = ""}, null)</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Authentication", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Register", "Register", "Authentication", new { area = "" }, null)</li>
                    }

                </ul>
            </div>
        </div>
    </div>
<div class="container body-content">
    @if (TempData.ContainsKey("Errors"))
    {
        <ul class="alert alert-danger alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
            @foreach (var error in (IEnumerable<string>
                    )TempData["Errors"])
            {
                <li>@error</li>
            }
        </ul>
    }
    @if (TempData.ContainsKey("Messages"))
    {
        <ul class="alert alert-info alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
            @foreach (var error in (IEnumerable<string>
                        )TempData["Messages"])
            {
                <li>@error</li>
            }
        </ul>
    }
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>